# Generated by Django 2.2.3 on 2019-10-09 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('published_date', models.DateTimeField()),
                ('page_count', models.IntegerField()),
                ('language', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ImageLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smallThumbnail', models.URLField()),
                ('thumbnail', models.URLField()),
                ('small', models.URLField()),
                ('medium', models.URLField()),
                ('large', models.URLField()),
                ('extraLarge', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='IndustryIdentifiers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
                ('identifier', models.TextField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stx_next_app.Book')),
            ],
        ),
        migrations.CreateModel(
            name='BookAuthors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stx_next_app.Author')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stx_next_app.Book')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='image_links',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stx_next_app.ImageLinks'),
        ),
        migrations.AddField(
            model_name='author',
            name='book',
            field=models.ManyToManyField(through='stx_next_app.BookAuthors', to='stx_next_app.Book'),
        ),
    ]
